In [1]:
(lambda x: x + 10)(10)

20

In [2]:
twice = lambda x: x*2
print(twice(10))

20


In [4]:
(lambda x: y=10; x+y)(1)

SyntaxError: invalid syntax (1727540298.py, line 1)

In [6]:
score = 90 
'A' if 90<score<=100 else 'B' if 80<score else 'C'

'B'

In [7]:
a = [_ for _ in range(5)]
b = [_ for _ in range(2, 11, 2)]
c = (list(map(lambda x, y: x * y, a, b)))
print(c)
((lambda x : x ** 2)(10))

[0, 4, 12, 24, 40]


100

In [8]:
a = [3, 2, 8, 22, 10, 7, 0, 11, 9, 9]
list(filter(lambda x: x % 3 == 0 and 0 < x < 10, a))

[3, 9, 9]

In [28]:
# class
class Student: 
    def __init__(self):
        self.hello = "안녕하세요."
        
    def greeting(self):
        print(self.hello)

In [1]:
# stu_a, stu_b 는 독립적으로 존재
stu_a = Student() # 클래스로부터 인스턴스 초기화
stu_b = Student() # 클래스로부터 인스턴스 초기화

NameError: name 'Student' is not defined

In [30]:
stu_a.greeting()

안녕하세요.


In [18]:
stu_a.name = "학생A"

In [31]:
stu_b.greeting()

안녕하세요.


In [19]:
print(stu_a.name)

학생A


In [21]:
print(stu_a.hello)

안녕하세요.


In [20]:
print(stu_b.name)

AttributeError: 'Student' object has no attribute 'name'

In [13]:
print(stu_b.hello)

NameError: name 'stu_b' is not defined

In [41]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

In [42]:
p1 = Person("name1", 40)
p2 = Person("name2", 32)

In [44]:
p1.__dict__

{'name': 'name1', 'age': 40}

In [45]:
p2.__dict__

{'name': 'name2', 'age': 32}

In [46]:
# p1.name ="name1"
# p1.age = 40

# p2.name = "name2"
# p2.age = 32

In [57]:
class Person:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
maria = Person("마리아", 20, "서울시 서초구 반포동")
maria.greeting()

print("이름:", maria.name)
print("나이:", maria.age)
print("주소:", maria.address)

안녕하세요. 제 이름은 마리아입니다.
이름: 마리아
나이: 20
주소: 서울시 서초구 반포동


In [53]:
class Person2:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")

In [55]:
maria = Person2("마리아", 23, "서울시 마포구")
maria.greeting()

안녕하세요. 제 이름은 마리아입니다.


In [56]:
maria.__dict__

{'hello': '안녕하세요.', 'name': '마리아', 'age': 23, 'address': '서울시 마포구'}

## 연습문제

Person 클래스로 maria, james라는 인스턴스를 생성합니다.  
maria와 james 두 사람의 나이, 이름, 주소를 받아와 객체에 저장하고 화면에  
출력해보세요.

In [72]:
class Person:
    def __init__(self, order, name, age, address):
        self.order = order
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"{self.order} 이름:{self.name}")
        print(f"{self.order} 나이:{self.age}")
        print(f"{self.order} 주소:{self.address}")
      
name1 = input("이름은 무엇인가요?")
age1 = input("나이는 무엇인가요?")
address1 = input("주소는 무엇인가요?")

name2 = input("이름은 무엇인가요?")
age2 = input("나이는 무엇인가요?")
address2 = input("주소는 무엇인가요?")

maria = Person("첫번째", name1, age1, address1)
james = Person("두번째", name2, age2, address2)

maria.greeting()
james.greeting()

이름은 무엇인가요? 마리아
나이는 무엇인가요? 20
주소는 무엇인가요? 서울시 강남구
이름은 무엇인가요? 제임스
나이는 무엇인가요? 21
주소는 무엇인가요? 서울시 구로구


첫번째 이름:마리아
첫번째 나이:20
첫번째 주소:서울시 강남구
두번째 이름:제임스
두번째 나이:21
두번째 주소:서울시 구로구


In [73]:
class ClassName:
    def __init__(self, param1, param2):
        self.attr1 = param1
        self.__attr2 = param2 # 비공개 속성

In [107]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)
        
    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount

In [100]:
lks = Person3("이기수", 88, "경기도 시흥", 20000)

In [101]:
lks.amount()

20000


In [102]:
lks.pay(10000)

In [104]:
lks.amount()

10000


In [105]:
lks.pay(15000)

돈이 모자랍니다.


In [77]:
print(lks.name)

이기수


In [78]:
print(lks.age)

88


In [79]:
print(lks.address)

경기도 시흥


In [81]:
print(lks.__wallet)

AttributeError: 'Person3' object has no attribute '__wallet'

In [86]:
class Person:
    def __init__(self, name, age, address, wallet):
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet # 변수 앞에 __를 붙여서 비공개 속성으로 만듦
        
maria = Person("마리아", 20, "서울시 서초구 반포동", 10000)
maria_wallet -= 10000 # 클래스 바깥에서 비공개 속성에 접근하면 에러 발생

NameError: name 'maria_wallet' is not defined

## 연습문제

사용자로부터 체력, 마나, AP를 입력받아 옵니다. 주어진 코드에서 애니(Annie)  
클래스를 작성하고 티버(tibbers) 스킬의 피해량이 출력되게 만들어보세요. 티버의  
피해량은 AP * 0.65 + 400이며 AP(Ability Power, 주문력)는 마법 능력치를 뜻합니다.  

> 실행결과:   
체력, 마나, AP를 입력하세요. 511.68 334.0 298  
티버: 피해량 593.7  

> 실행결과:  
체력, 마나, AP를 입력하세요. 1803.68 1184.0 645  
티버: 피해량 819.25  

In [115]:
class Annie:
    def __init__(self, hp, mp, ap):
        self.hp = hp
        self.mp = mp
        self.ap = ap
        
    def tibbers(self):
        damage = self.ap * 0.65 + 400
        print(f'티버: 피해량 {damage}')
        
hp, mp, ap = map(float,input("체력, 마나, AP를 입력하세요.").split(" "))
annie = Annie(hp, mp, ap)
annie.tibbers()

체력, 마나, AP를 입력하세요. 511.68 334.0 298


티버: 피해량 593.7


# NumPy

In [121]:
import numpy as np

## 1차원 배열 만들기

In [122]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
ar.shape

(10,)

In [124]:
!conda list

# packages in environment at C:\Users\wkddl\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0    

In [ ]:
# NumPy를 임포트
# jupyter lab에서 1회만 실행하면 그 아래 코드에선 다 사용 가능합니다.
import numpy as np

In [126]:
ar = np.array([_ for _ in range(10)])

In [127]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
ar.shape

(10,)

In [129]:
type(ar)

numpy.ndarray

In [130]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [132]:
import numpy as np
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [133]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [136]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [134]:
ar.dtype

dtype('int32')

In [135]:
ar2.dtype

dtype('float64')

In [139]:
# 01010101 -> 8bit == 1byte

In [144]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8') # int8bytes --> int8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [143]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [150]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <U8로 타입이 지정되었다.
ar5 = np.array(["가나다라마", "바사아", "자", "차카"], 'U8') 
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']
<U8


In [156]:
x = np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [157]:
x[0] + x[1]

3.0

In [160]:
x = np.array([1, 2, 3], dtype = 'U')
x.dtype

dtype('<U1')

In [161]:
x[0] + x[1]

'12'

In [162]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\wkddl\AppData\Local\Temp\ipykernel_12056\2068585620.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\wkddl\AppData\Local\Temp\ipykernel_12056\2068585620.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [163]:
np.log(0)

C:\Users\wkddl\AppData\Local\Temp\ipykernel_12056\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [164]:
np.exp(-np.inf)

0.0

## 벡터화 연산(Vectoriaed Operaton

In [165]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [166]:
answer = [2 * d for d in data]

In [167]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [169]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [174]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [175]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [176]:
2 * a + b

array([12, 24, 36])

In [177]:
a == 2

array([False,  True, False])

In [178]:
b > 10

array([False,  True,  True])

In [179]:
(a == 2) & (b > 10)

array([False,  True, False])

## 2차원 배열 만들기

In [180]:
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [181]:
c.shape

(2, 3)

In [182]:
# 행의 갯수
len(c)

2

In [183]:
len(c[0])

3

## 연습문제

넘파이를 사용하여 다음과 같은 행렬을 만들어보세요.

> 실행결과 :  
array([[10, 20, 30, 40],  
       [50, 60, 70, 80]])

In [185]:
x = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기

In [186]:
# 2 x 3 x 4
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18], 
               [19, 20, 21, 22]]])

In [188]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [189]:
d.shape

(2, 3, 4)

In [190]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [191]:
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [192]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


## 배열의 인덱싱

In [193]:
list_sample = [[0, 1, 2], [3, 4, 5]]

In [199]:
list_sample[0][0]

1

In [200]:
list_sample[0][1]

2

In [194]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [195]:
a[0, 0] # 첫번째 행의 첫번째 열

0

In [196]:
a[0, 1] # 첫번째 행의 두번째 열

1

In [197]:
a[-1, -1] # 마지막 행의 마지막 열

5

## 배열의 슬라이싱

In [201]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [207]:
a = np.array([_ for _ in range(8)]).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [202]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [203]:
a[:, 1] # 두번째 열 전체

array([1, 5])

In [204]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [205]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

# 연습 문제

다음의 행렬이 주어졌을 때 1~5까지 문제를 풀어보세요.

```python
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7을 인덱싱한다.
2. 이 행렬에서 값 14을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7]을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12]을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]]을 슬라이싱한다.

In [234]:
m = np.array([i for i in range(15)]).reshape(3, 5)

print(m[1, 2])
print(m[2, 4])
print(m[1, 1:3])
print(m[1:3, 2])
print(m[:2, 3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


## 배열 생성

In [235]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [236]:
c = np.zeros((5, 2), dtype = "i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [238]:
d = np.zeros(5, dtype = "U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [239]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [240]:
e = np.ones((2, 3, 4), dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [241]:
f = np.ones_like(b, dtype = "f")
f

array([1., 1., 1.], dtype=float32)

In [243]:
g = np.empty((4, 3))
g

array([[1.06123595e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.14587773e-312, 1.04082753e-047],
       [5.45214695e-090, 7.11286183e-038, 8.46402186e+164],
       [2.21603337e+160, 3.99910963e+252, 1.01334814e-070]])

In [244]:
np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [245]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [246]:
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [254]:
np.logspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [251]:
ex = np.linspace(0, 100, 15)
ex

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [253]:
ex2 = np.logspace(0, 100, 5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

## 전치 연산

In [255]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [256]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형

In [257]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [258]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [260]:
ex3 = np.arange(12)
ex3.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [261]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [262]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [263]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [264]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [265]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [266]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [268]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [269]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 배열 연결

In [270]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [271]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [272]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [273]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [275]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [279]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [280]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [281]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [282]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [283]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [284]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [285]:
c.shape

(2, 3, 4)

In [286]:
c = np.stack([c1, c2], axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [287]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [288]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [289]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [290]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## 연습 문제

앞서 배운 내용을 활용해서 다음과 동일한 배열을 만들어보세요.

In [308]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.array([_ for _ in range(10, 151, 10)]).reshape(3, 5)

d = np.hstack([a, b])
e = np.vstack([d, c])
f = np.vstack([e, e])
f

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])