# Class, Numpy 복습

### 연습문제

현재까지 계산한 값을 속성 value로 갖는 계산기 클래스를 만들고자 합니다.

- value 속성의 초기값은 0으로 갖습니다.
- add 메서드는 value 값에 인수로 받은 값을 가산합니다.
- minus 메서드는 value 값에 인수로 받은 값을 감산합니다.
- show_value 메서드는 다음과 같이 현재 값을 출력합니다.  "현재 값은 000입니다."
- add와 minus는 가변 인자를 활용하여 시퀀스로 처리합니다.  
- 인수가 없는 경우 "숫자를 입력해주세요"라고 출력합니다.
- 숫자가 아닌 값에 대해서 처리는 따로 하지 않습니다.

```python
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()
```
> 현재 값은 80입니다.
```python
c.add()
```
> 숫자를 입력해주세요.
```python
c.minus([10, 20])
c.show_value()
```
> 현재 값은 50입니다.
```python
c.add(range(1, 6))
c.show_value()
```
> 현재 값은 65입니다.

In [181]:
import numpy as np

class Calculator:
    
    def __init__(self):
        self.value = 0
    
    def add(self, *number):
        num = (np.array(number))
        if len(number) == 0:
            print("숫자를 입력해주세요")
        self.value += np.sum(num)
        
    def minus(self, *number):
        num = (np.array(number))
        if len(number) == 0:
            print("숫자를 입력해주세요")
        self.value -= np.sum(num)
            
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')

In [182]:
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()
c.add()
c.minus([10,20])
c.show_value()
c.add(range(1,6))
c.show_value()

현재 값은 80입니다.
숫자를 입력해주세요
현재 값은 50.0입니다.
현재 값은 65.0입니다.


In [164]:
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()

현재 값은 80입니다.


In [153]:
c.add()

숫자를 입력해주세요


In [154]:
c.minus([10, 20])
c.show_value()

현재 값은 50.0입니다.


In [155]:
c.add(range(1, 6))
c.show_value()

현재 값은 65.0입니다.


In [161]:
class Calculator():
    def __init__(self):
        self.value = 0
    def add(self,*n):
        if len(n) == 0:
            print("숫자를 입력해주세요")
        for i in n:
            if type(i) == range:
                for j in i:
                    self.value += j
            else:
                self.value += sum(n)
    def minus(self,*n):
        if len(n) ==0 :
            print("숫자를 입력해주세요.")
        for i in n:
            if type(i) == list:
                for j in i:
                    self.value -= j
            else:
                self.value -= sum(n)
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")
        
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()
c.add()
c.minus([10,20])
c.show_value()
c.add(range(1,6))
c.show_value()

현재 값은 80입니다.
숫자를 입력해주세요
현재 값은 50입니다.
현재 값은 65입니다.


In [175]:
import numpy as np

class Calculator:
    
    def __init__(self):
        self.value = 0
    
    def add(self, *number):
        if len(number) > 0:
            num = (np.array(number))
            self.value += np.sum(num)
        else:
            print("숫자를 입력해주세요")
        
    def minus(self, *number):
        if len(number) > 0:
            num = (np.array(number))
            self.value -= np.sum(num)
        else:
            print("숫자를 입력해주세요")
            
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')

In [176]:
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()
c.add()
c.minus([10,20])
c.show_value()
c.add(range(1,6))
c.show_value()

현재 값은 80입니다.
숫자를 입력해주세요
현재 값은 50입니다.
현재 값은 65입니다.


In [178]:
import numpy as np
class Calculator:
    def __init__(self):
        self.value = 0
    def add(self,*num):
        if len(num) == 0:
            print(f'숫자를 입력해주세요.')
        else:
            self.value += np.sum(num)
    def minus(self,*num):
        if len(num) == 0:
            print(f'숫자를 입력해주세요.')
        else:
            self.value -= np.sum(num)
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')
c=Calculator()
c.add(100)
c.minus(20)
c.show_value()
c.add()
c.minus([10,20])
c.show_value()
c.add(range(1,6))
c.show_value()

현재 값은 80입니다.
숫자를 입력해주세요.
현재 값은 50입니다.
현재 값은 65입니다.


In [237]:
hasattr(range, "__iter__") # 이 True이면 iterable이라는 의미다.

True

In [238]:
sum(range(10))

45

# NumPy

## 벡터화 연산

In [195]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [197]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 5.56 ms


In [188]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [198]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [199]:
%%time
z = x + y

Wall time: 0 ns


In [200]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [201]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [202]:
a == b

array([False,  True, False,  True])

In [203]:
a >= b

array([False,  True,  True,  True])

In [204]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [205]:
np.all(a == b)

False

In [206]:
np.all(a == c)

True

## 스칼라와 벡터/행렬의 곱셈

In [208]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [210]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅

In [213]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [214]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [216]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [217]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [219]:
x + y

array([2, 2, 2, 2, 2])

In [221]:
x + 1

array([2, 2, 2, 2, 2])

## 차원 축소 연산

In [224]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [225]:
np.sum(x)

10

In [227]:
x.sum()

10

In [228]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
x.sum(axis=0) # axis=0은 행 간의 연산 결과를 구한다.

array([12, 15, 18, 21])

In [230]:
x.sum(axis=1) # axis=1은 열 간의 연산 결과를 구한다.

array([ 6, 22, 38])

In [231]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [232]:
x.min()

0

In [233]:
np.min(x)

0

In [234]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [235]:
np.min(x, axis = 1)

array([[ 0,  1],
       [10, 11]])

In [236]:
x.min(axis = 2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [239]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [240]:
x.argmin()

0

In [241]:
np.argmin(x)

0

In [242]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [243]:
np.argmin(x, axis = 1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [245]:
x.argmin(axis = 2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [246]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [247]:
x.max()

19

In [248]:
np.max(x)

19

In [249]:
x.max(axis = 0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [250]:
np.max(x, axis = 1)

array([[ 8,  9],
       [18, 19]])

In [251]:
x.max(axis = 2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [252]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [253]:
x.argmax()

19

In [254]:
np.argmax(x)

19

In [255]:
x.argmax(axis = 0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [256]:
np.argmax(x, axis = 1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [257]:
x.argmax(axis = 2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [258]:
x = np.array([1, 2, 3, 1])

In [259]:
x.mean()

1.75

In [260]:
np.median(x)

1.5

In [261]:
np.all([True, True, False])

False

In [262]:
np.any([True, True, True])

True

In [263]:
a = np.zeros((100, 100), dtype=np.int64)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [264]:
np.any(a != 0)

False

In [265]:
np.all(a == a)

True

In [266]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [267]:
((a <= b) & (b <= c)).all()

True

### 연습문제

실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을  
구한다.

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

```python
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])
```

In [268]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [270]:
practice.max()

9.0

In [285]:
practice.sum(axis = 0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [282]:
practice.max(axis = 0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [283]:
practice.mean(axis = 1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [284]:
practice.min(axis = 1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

## 정렬

In [286]:
a = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [287]:
np.sort(a) # axis = -1 또는 axis = 1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [288]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [289]:
a = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [290]:
a.sort(axis = 1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [296]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [297]:
a[j]

array([12, 25, 38, 42])

In [298]:
np.sort(a)

array([12, 25, 38, 42])

## 고급 인덱싱

In [300]:
a = np.array([[1, 2],[3, 4],[5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [302]:
print(a[[0,1,2], [0,1,0]]) # a[0,0], a[1,1] a[2,0]을 인덱스로 하는 1차원 배열(shape=(3,))을 출력해준다.

[1 4 5]


In [304]:
a = np.array([[1, 2],[3, 4],[5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [305]:
print(a[:, [0, 1, 0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


### 연습문제

다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을  
적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬해보세요.

```python
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])
```

In [322]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])
eng_sco = scores[1, :]
j = np.argsort(eng_sco)
eng_sco[j]
j

array([0, 3, 1, 2], dtype=int64)

In [327]:
print(scores[:, j])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [329]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])
j = np.argsort(scores[1, :])
scores[:, j]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 기술 통계

In [332]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 
              2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [334]:
np.mean(x) # 평균

4.8076923076923075

In [335]:
np.var(x) # 분산

115.23224852071006

In [336]:
np.var(x, ddof=1) # 비편향 분산. 추후 공부하게 된다.

119.84153846153846

In [337]:
np.std(x) # 표준 편차

10.734628476137871

In [338]:
np.median(x) # 중앙값

5.0

## 사분위수

In [341]:
np.min(x) # 최소값

-24

In [343]:
np.median(x) # 중앙값

5.0

In [345]:
np.percentile(x, 0) # 최소값

-24.0

In [351]:
np.percentile(x, 25) # 1 사분위 수

0.0

In [352]:
np.percentile(x, 50) # 2 사분위 수

5.0

In [353]:
np.percentile(x, 75) # 3사분위 수

10.0

In [354]:
np.percentile(x, 100) # 최대값

23.0

## 난수 발생과 카운팅

### 시드 설정하기

In [365]:
np.random.seed(0)

In [366]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [367]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [368]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [369]:
np.random.seed(0)

In [370]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [371]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [372]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

### 데이터의 순서 바꾸기

In [374]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [375]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

### 데이터 샘플링

In [377]:
np.random.choice(5, 5, replace=False) # shuffle 명령과 같다.

array([1, 4, 0, 3, 2])

In [378]:
np.random.choice(5, 3, replace=False) # 3개만 선택

array([2, 1, 3])

In [379]:
np.random.choice(5, 10) # 반복해서 10개 선택

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [384]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 3, 3, 3, 3, 3, 3, 2, 3])

### 난수 생성

In [385]:
np.random.rand(10)

array([0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164,
       0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438])

In [386]:
np.random.rand(3, 5)

array([[0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673],
       [0.35944446, 0.48089353, 0.68866118, 0.88047589, 0.91823547],
       [0.21682214, 0.56518887, 0.86510256, 0.50896896, 0.91672295]])

In [387]:
np.random.randn(10)

array([ 0.42830357,  0.99627783, -0.49114966,  0.71267817,  1.11334035,
       -2.15367459, -0.41611148, -1.07089699,  0.22113881, -1.12305712])

In [388]:
np.random.randn(3, 5)

array([[-1.05075796,  1.01207905,  1.54371643, -0.40211489,  0.8647491 ],
       [-0.22686923,  0.81116027,  0.28779461, -0.53846816,  1.9084621 ],
       [-0.475776  ,  1.44073112, -1.14907568,  0.80571455,  1.75610703]])

In [392]:
np.random.randint(10, size=10)

array([8, 2, 3, 9, 7, 5, 3, 4, 5, 3])

In [393]:
np.random.randint(10, 20, size=10)

array([13, 17, 19, 19, 19, 17, 13, 12, 13, 19])

In [394]:
np.random.randint(10, 20, size=(3, 5))

array([[17, 17, 15, 11, 12],
       [12, 18, 11, 15, 18],
       [14, 10, 12, 15, 15]])

### 연습 문제

동전 100번 던진 결과를 넘파이에 난수를 발생시켜서 시뮬레이션해보려 합니다. 앞면을  
숫자 1, 뒷면을 숫자 0으로 가정하고 난수를 발생시켜보세요. 이때 앞면이 나올 확률을  
구하는 프로그램을 구현해보세요.(seed는 0으로 합니다.)

> 실행 결과:  
0.56

In [402]:
np.random.seed(0)
x = np.random.choice(2, 100)
front_count = 0

for _ in x:
    if _ == 1:
        front_count += 1
front_count / 100

0.56

### 연습 문제

주사위는 1부터 6까지의 숫자를 가집니다. 이 주사위를 100번 던져서 나오는 숫자를  
넘파이 난수를 발생시켜서 시뮬레이션하고 나오는 숫자의 평균을 구해보세요.(seed는  
으로 설정합니다.)

> 실행 결과:  
3.42

In [416]:
np.random.seed(0)
x = [np.random.randint(1, 7) for _ in range(100)]
np.mean(x)

3.42

## 정수 데이터 카운팅

In [417]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [421]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [422]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [423]:
count

array([2, 2, 1], dtype=int64)

In [425]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)